recs_categories = [
    "Arts and Crafts",
    "Automotive",
    "Baby",
    "Bakeware",
    "Beauty and Personal Care",
    "Bedroom Furniture",
    "Computers",
    "Cookware",
    "Dining and Entertaining",
    "Electronics",
    "Entryway Furniture",
    "Food",
    "Health and Household",
    "Home Entertainment Furniture",
    "Home and Kitchen",
    "Household Essentials",
    "Industrial and Scientific",
    "Kitchen and Table Linens",
    "Kitchen Appliances",
    "Kitchen and Dining Furniture",
    "Kitchen Storage",
    "Kitchen Tools and Gadgets",
    "Living Room Furniture",
    "Luggage",
    "Mattresses",
    "Men's Fashion",
    "Office Furniture",
    "Patio Furniture",
    "Patio and Garden",
    "Pet Supplies",
    "Smart Home",
    "Specialty Kitchen Appliances",
    "Sports, Fitness and Outdoors",
    "Tools and Home Improvement",
    "Toys and Games",
    "Women's Fashion"
]