category = {
    "Electronics": [
        "Accessories & Supplies",
        "Camera & Photo",
        "Car & Vehicle Electronics",
        "Cell Phones & Accessories",
        "Computers & Accessories",
        "GPS & Navigation",
        "Headphones",
        "Home Audio",
        "Office Electronics",
        "Portable Audio & Video",
        "Security & Surveillance",
        "Service Plans",
        "Television & Video",
        "Video Game Consoles & Accessories",
        "Wearable Technology",
        "eBook Readers & Accessories"
    ],
    "Computers": [
        "Computer Accessories & Peripherals",
        "Computer Components",
        "Computer & Tablets",
        "Data Storage",
        "External Components",
        "Laptop Accessories",
        "Monitors",
        "Networking Products",
        "Power Strips & Surge Protectors",
        "Printers",
        "Scanners",
        "Servers",
        "Tablet Accessories",
        "Tablet Replacement Parts",
        "Warranties & Services"
    ],
    "Smart Home": [
        "Amazon Smart Home",
        "Lighting",
        "Door Locks",
        "Cameras",
        "Plugs",
        "Other Smart Solutions",
        "Thermostats",
        "Security Systems",
        "Televisions",
        "Speakers",
        "Voice Assistants",
        "Kitchen",
        "Vacuums",
        "Printers & PC",
        "Network & Wifi",
        "New to Smart Home"
    ],
    "Arts & Crafts": [
        "Painting, Drawing & Art Supplies",
        "Beading & Jewelry Making",
        "Crafting",
        "Fabric",
        "Fabric Decorating",
        "Knitting & Crochet",
        "Needlework",
        "Organization, Storage & Transport",
        "Printmaking",
        "Scrapbooking & Stamping",
        "Sewing",
        "Party Decorations & Supplies",
        "Gift Wrapping Supplies"
    ],
    "Automotive": [
        "Car Care",
        "Car Electronics & Accessories",
        "Exterior Accessories",
        "Interior Accessories",
        "Lights & Lighting Accessories",
        "Motorcycle & Powersports",
        "Oils & Fluids",
        "Paint & Paint Supplies",
        "Performance Parts & Accessories",
        "Replacement Parts",
        "RV Parts & Accessories",
        "Tires & Wheels",
        "Tools & Equipment",
        "Automotive Enthusiast Merchandise",
        "Heavy Duty & Commercial Vehicle Equipment"
    ],
    "Baby": [
        "Activity & Entertainment",
        "Apparel & Accessories",
        "Baby & Toddler Toys",
        "Baby Care",
        "Baby Stationery",
        "Car Seats & Accessories",
        "Diapering",
        "Feeding",
        "Gifts",
        "Nursery",
        "Potty Training",
        "Pregnancy & Maternity",
        "Safety",
        "Strollers & Accessories",
        "Travel Gear",
        {
            "Feeding": [
                "Bottle Feeding",
                "Breastfeeding",
                "Highchairs & Boosters",
                "Pacifiers",
                "Bibs & Burp Cloths",
                "Toddler Feeding",
                "Baby Formula",
                "Sippy Cups",
                "Baby Food",
                "Toddler Drinks & Formula",
                "Baby Feeding Guide",
            ],
            "Car Seats": [ 
                "Infant Car Seats",
                "Convertible Car Seats",
                "Booster Car Seats",
                "Car Seat Accessories",
            ],
            "Strollers": [ 
                "Travel Systems",
                "Umbrella Strollers",
                "Double Stollers",
                "Jogging Stollers",
                "Stroller Accessories",
            ],
            "Nursery": [  
                "Cribs",
                "Baby Bedding",
                "Nursery Decor",
                "Bassinets",
                "Gliders & Rockers",
                "Dressers",
                "Changing Tables",
                "Changing Pads & Covers",
                "Crib Mattresses"
            ],
            "Play & travel gear": [ 
                "Swings",
                "Bouncers",
                "Playards",
                "Gyms & Playmats",
                "Activity Centers",
                "Walkers",
                "Jumpers",
                "Baby Carriers"
            ],
            "Diapering": [ 
                "Diapers",
                "Baby Wipes",
                "Diaper Bags",
                "Baby Care"
            ],
            "Bath & Potty": [ 
                "Baby Bath",
                "Potty Training",
            ],
            "Health & Safety": [ 
                "Baby Health",
                "Cold & Flu Prevention",
                "Baby Monitors",
                "Baby Proofing",
                "Baby Gates"
            ],
            "Toddler Room": [ 
                "Classic Toddler Beds",
                "Character Toddler Beds",
                "Toddler Bedding Sets",
                "Toddler Seating"
            ]
        }
    ],
    "Beauty & personal care": [
        "Makeup",
        "Skin Care",
        "Hair Care",
        "Fragnance",
        "Foot, Hand & Nail Care",
        "Tools & Accessories",
        "Shave & Hair Removal",
        "Personal Care",
        "Oral Care"
    ],
    "Women's Fashion": [
        "Clothing",
        "Shoes",
        "Jewelry",
        "Watches",
        "Handbags",
        "Bras, Panties & Lingerie",
        "Pajamas & Loungewear",
        "Maternity",
        "Accessories",
        "Men's Fashion",
        "Girls' Fashion",
        "Boys' Fashion",
    ],
    "Men's Fashion": [
        "Clothing",
        "Shoes",
        "Watches",
        "Pajamas & Robes",
        "Accessories & Bags",
        "Women's Fashion",
        "Girls' Fashion",
        "Boys' Fashion"
    ],
    "Girls' Fashion": [
        "Clothing",
        "Shoes",
        "Watches",
        "Accessories",
        "Women's Fashion",
        "Girls' Fashion",
        "Boys' Fashion",
        "School Uniforms"
        "Jewelry"
    ],
    "Boys' Fashion": [
        "Clothing",
        "Shoes",
        "Watches",
        "Accessories",
        "Women's Fashion",
        "Girls' Fashion",
        "Boys' Fashion",
        "School Uniforms"
        "Jewelry"
    ],
    "Health & Household": [
        "Baby & Child Care",
        "Health Care",
        "Household Supplies",
        "Medical Supplies & Equipment",
        "Oral Care",
        "Personal Care",
        "Sexual Wellness",
        "Sports Nutrition",
        "Stationery & Gift Wrapping Supplies",
        "Vision Care",
        "Vitamins & Dietary Supplements",
        "Wellness & Relaxation"
    ],
    "Home and Kitchen": [
        "Kids' Home Store",
        "Kitchen & Dining",
        "Bedding",
        "Bath",
        "Furniture",
        "Appliances",
        "Patio & Garden",
        "Mattresses",
        "Rugs",
        "Curtains",
        "Blinds & Shades",
        "Wall Art",
        "Wall Decor",
        "Candles & Home Fragrance",
        "Home Decor",
        "Wall Art",
        "Lighting & Ceiling Fans",
        "Seasonal Decor",
        "Event & Party Supplies",
        "Heating, Cooling & Air Quality",
        "Irons & Steamers",
        "Vacuums & Floor Care",
        "Storage & Organization",
        "Cleaning Supplies",
        {
            "Others" : [ 
                "Area Rugs",
                "Bed Frames",
                "Blenders",
                "Bookcases",
                "Coffee Makers",
                "Coffee Tables",
                "Cube Storage",
                "Curtains",
                "Curtain Rods",
                "Desks",
                "Dressers",
                "Floor Lamps",
                "Folding Tables",
                "Futons",
                "LED Light Strips",
                "Mason Jars",
                "Microwaves",
                "Mini Fridges",
                "Nightstands",
                "Office Chairs",
                "Pillows",
                "Shower Curtains",
                "Storage Bins",
                "TV Stands",
                "Vacuums"
            ]
        }
    ],
    "Pation & Garden" : [
        {
            "Patio Furniture" : [
                "Patio Chairs & Seating",
                "Patio Sets",
                "Outdoor Dining Furniture",
                "Outdoor Lounge Furniture",
                "Outdoor Bar Furniture",
                "Patio Tables",
                "Beach Chairs",
                "Hammocks",
                "Picnic Tables",
                "Porch Swings"
            ],
            "Garden Center": [
                "Pots & Planters",
                "Greenhouses",
                "Garden Tools & Equipment",
                "Landscaping & Lawn Care",
                "Watering & Irrigation",
                "Composters",
                "Hydroponics"
            ],
            "Grills & Outdoor Cooking": [
                "Flat Top Grills & Outdoor Griddles",
                "Gas Grills",
                "Portable Grills",
                "Pellet Grills",
                "Grill Accessories",
                "Combo Grills",
                "Charcoal Grills",
                "Smokers",
                "Grill Fuels",
                "Fryers & Outdoor Cooking Pots"
            ],
            "Patio & Outdoor Decor": [
                "Outdoor Cushions",
                "Outdoor Pillows",
                "Outdoor Rugs",
                "Bird Feeders & Houses",
                "Fountains",
                "Garden Statues",
                "Wind Chimes"
            ],
            "Sheds & Outdoor Storage": [
                "Sheds",
                "Deck Boxes",
                "Patio Furniture Covers",
                "Carports"
            ],
            "Outdoor Heating": [
                "Fire Pits",
                "Fire Pit Tables",
                "Patio Heaters",
                "Chimineas",
                "Outdoor Fireplaces",
                "Fire Pit Accessories",
                "Tiki Torches",
                "Firewood Racks"
            ],
            "Outdoor Shade": [
                "Patio Umbrellas",
                "Umbrella Stands & Bases",
                "Gazebos",
                "Pergolas",
                "Awnings",
                "Outdoor Blinds & Shades",
                "Shade Sails"
            ],
            "Outdoor Lighting": [
                "String Lights",
                "Landscape Lighting",
                "Outdoor Security Lights",
                "Lanterns",
                "Outdoor Ceiling Fans"
            ],
            "Plants, Flowers, Trees": [],
            "Outdoor Power Equipment": [],
            "Patio & Garden Savings": [ 
                "Patio & Garden Clearance",
                "Patio & Garden Rollback"
            ]
        }
    ],
    "Industrial and Scientific": [
        "Abrasive & Finishing Products",
        "Additive Manufacturing Products",
        "Commercial Door Products",
        "Cutting Tools",
        "Fasteners",
        "Filtration",
        "Food Service Equipment & Supplies",
        "Hydraulics, Pneumatics & Plumbing",
        "Industrial Electrial",
        "Industrial Hardware",
        "Industrial Power & Hand Tools",
        "Janitorial & Sanitation Supplies",
        "Lab & Scientific Products",
        "Material Handling Products",
        "Occupational Health & Safety Products",
        "Packaging & Shipping Supplies",
        "Power Transmission Products",
        "Professional Dental Supplies",
        "Raw Materials",
        "Retail Store Fixtures & Equipment",
        "Robotics",
        "Science Education",
        "Tapes, Adhesives & Sealants",
        "Test, Measure & Inspect"
    ],
    "Luggage": [
        "Carry-ons",
        "Backpacks",
        "Garment bags",
        "Travel Totes",
        "Luggage Sets",
        "Laptop Bags",
        "Suitcases",
        "Kids Luggage",
        "Messenger Bags",
        "Umbrellas",
        "Duffles",
        "Travel Accessories"
    ],
    "Movies & Television": [
        "Movies",
        "TV Shows",
        "Blu-ray",
        "4K Ultra HD",
        "Best Sellers",
        "Today's Deals",
        "New Releases",
        "Pre-orders",
        "Kids & Family",
        "Prime Video"
    ],
    "Pet supplies": [
        "Dogs",
        "Cats",
        "Fish & Aquatic Pets",
        "Birds",
        "Horses",
        "Reptiles & Amphibians",
        "Small Animals"
    ],
    "Software": [
        "Accounting & Finance",
        "Antivirus & Security",
        "Business & Office",
        "Children's",
        "Design & Illustration",
        "Digital Software",
        "Education & Reference",
        "Games",
        "Lifestyle & Hobbies",
        "Music",
        "Networking & Servers",
        "Operating Systems",
        "Photography",
        "Programming & Web Development",
        "Tax Preparation",
        "Utilities",
        "Video"
    ],
    "Sports and Outdoors": [
        "Sports & Outdoors",
        "Outdoor Recreation",
        "Sports & Fitness",
        "Fan Shop"
    ],
    "Tools & Home Improvement": [
        "Tools & Home Improvement",
        {
            "Home Improvement": [
                "Bathroom Renovation",
                "Building Materials",
                "Ceiling Fans",
                "Doors & Gates",
                "Electrical",
                "Fasteners",
                "Flooring",
                "Floor & Wall Tiles",
                "Garage & Storage",
                "Generators",
                "Hardware",
                "Home Safety",
                "Kitchen Renovation",
                "Ladders",
                "Light Bulbs",
                "Outdoor Trash Cans",
                "Paint",
                "Paint Tools & Supplies",
                "Plumbing",
                "Renewable Energy",
                "Wall Coverings",
                "Wall Lights & Fixtures",
                "Wallpaper",
                "Water Purification & Dispensers",
                "Wet/Dry Vacs",
                "Windows"
            ],
            "Heating": [
                "Fireplaces",
                "Heaters",
                "Stoves",
                "Water Heaters",
                "Weatherproofing"
            ],
            "Cooling": [
                "Air Conditioners",
                "Evaporative Coolers",
                "Fans",
                "Portable Air Conditioners",
                "Wall Air Conditioners",
                "Window Air Conditioners"
            ],
            "Air Quality": [ 
                "Air Filters",
                "Air Purifiers",
                "Dehumidifiers",
                "Humidifiers"
            ],
            "Tools": [
                "Air Tools",
                "Hand Tools",
                "Personal Protective Equipment",
                "Power Tools",
                "Tool Equipment",
                "Tool Storage"
            ]
        },
        "Appliances",
        "Building Supplies",
        "Electrical",
        "Hardware",
        "Kitchen & Bath Fixtures",
        "Light Bulbs",
        "Lighting & Ceiling Fans",
        "Measuring & Layout Tools",
        "Painting Supplies & Wall Treatments",
        "Power & Hand Tools",
        "Rough Plumbing",
        "Safety & Security",
        "Storage & Home Organization",
        "Welding & Soldering"
    ],
    "Toys and Games": [
        "Action Figures & Statues",
        "Arts & Crafts",
        "Baby & Toddler Toys",
        "Building Toys",
        "Dolls & Accessories",
        "Dress Up & Pretend Play",
        "Kids' Electronics",
        "Games",
        "Grown-Up Toys",
        "Hobbies",
        "Kid's Furniture, Decor & Storage",
        "Learning & Education",
        "Novelty & Gag Toys",
        "Party Supplies",
        "Puppets",
        "Puzzles",
        "Sports & Outdoor Play",
        "Stuffed Animals & Plush Toys",
        "Toy Remote Control & Play Vehicles",
        "Tricycles, Scooters & Wagons",
        "Video Games"
    ],
    "Video Games": [
        "Video Games",
        "PlayStation 4",
        "PlayStation 3",
        "Xbox One",
        "Xbox 360",
        "Nintedo Switch",
        "Wii U",
        "Wii",
        "PC",
        "Mac",
        "Nintedo 3DS & 2DS",
        "Nintedo DS",
        "PlayStation Vita",
        "Sony PSP",
        "Retro Gaming & Microconsoles",
        "Accessories",
        "Digital Games",
        "Kids & Family",
        "Esports Arena",
        "Loot boxes"
    ],
    "Food": [
        "Food Gifts",
        "Christmas Candy",
        "Coffee",
        "Beverages",
        "Snacks",
        "Breakfast & Cereal",
        "Meals",
        "Condiments",
        "Candy & Gum",
        "Baking Center",
        "Premimum Chocolate Shop",
        "Premium Coffee Shop",
        "Plant Based Foods",
        "Gluten Free Foods",
        "Asian Market"
    ],
    "Household Essentials": [ 
        "Laundry Room",
        "Kitchen",
        "Bathroom",
        "Paper & Plastic",
        "Cleaning Supplies",
        "Air Fresheners",
        "Batteries",
        "Pest Control",
        "As Seen On TV",
        "Light Bulbs"
    ],
    "Pet Supplies": [ 
        "Dog Supplies",
        "Cat Supplies",
        "Fish Supplies",
        "Small Animal Supplies",
        "Reptile Supplies",
        "Bird Supplies",
        "Horse Supplies",
        "Farm Animal Supplies"
    ],
    "Pharmacy, Health & Personal Care": {
        "Health": [
            "Medicine Cabinet",
            "Children's Health",
            "Pain Relievers",
            "Allergy",
            "Digestive Health",
            "Diabetes Management",
            "Incontience",
            "Home Health Care",
            "Massagers & Spa",
            "Sexual Wellness",
            "Equate",
            "Sleep Better",
            "Quit Smoking"
        ],
        "Personal Care": [
            "Feminine Care",
        ],
        "Oral Care": [ 
            "Electric Toothbrushes"
        ],
        "Shave": [  
            "Electic Shavers",
            "Razors & Blades"
        ],
        "Bath & Body": [
            "Body Wash",
            "Lotions",
            "Deodorant & Antiperspirant"
        ],
        "Health Services": [
        {
            "Pharmacy": [
                "Refill Prescriptions",
                "Transfer Prescription",
                "Flu Shots & Immunizations",
                "Pet Pharmacy"
            ]
        }, 
        "Vision Center",
        "Health Clinics",
        "Health Insurance Resources"
        ],
        "Wellness": [ 
            "Vitamins & Supplements",
            "Protein & Fitness",
            "Weight Management",
            "Keto Diet"
        ]
    },
    "Beauty": [
        "Makeup",
        "Hair Care",
        "Hair Color",
        "Hair Tools",
        "Skincare",
        "Fragrance",
        "Nail Care",
        "Beauty Tech & Tools"
    ],
    "Sports, Fitness & Outdoors": {
        "Bikes": [  
            "Adult Bikes",
            "Kids Bikes",
            "Electric Bikes",
            "Performance Cycling"
        ],
        "Exercise & Fitness": [  
            "Walk and Run",
            "Premium Fitness",
            "Treadmills",
            "Boxing and MMA",
            "Exercise Machines",
            "Fitness Accessories",
            "Pilates",
            "Sports Recovery",
            "Strength Training",
            "Yoga"
        ],
        "Outdoor Sports": [  
            "Boats and Marine",
            "Fishing",
            "Hunting",
            "Kayak and Paddle",
            "Recreational Shooting",
            "Snowsports",
            "Shooting Supplies",
            "Water Sports",
            "Fishing by Location"
        ],
        "Sports": [ 
            "Baseball",
            "Basket",
            "Football",
            "Golf",
            "Hockey",
            "Soccer",
            "Tennis",
            "Volleyball"
        ],
        "Recreation": [ 
            "Game Room",
            "Trampolines",
            "Outdoor Games",
            "Skateboards and Skates"
        ],
        "Camping and Hiking": [ 
            "Air Mattresses",
            "Backpacks",
            "Camp Kitchen",
            "Camping Furniture",
            "Canopies and Shelters",
            "Climbing",
            "Coolers",
            "Drinkware",
            "Lighting",
            "Outdoor Clothing",
            "Outdoor Footwear",
            "Sleeping Bags",
            "Tents",
            "Ozark Trail"
        ]
    },
    "Auto, Tires and Industrial": {
        "Auto Buying": [],
        "Auto Services": [],
        "Tires": [],
        "Batteries and Accessories": [],
        "Auto Interior": [],
        "Auto Exterior": [
            "Towing Hitches and Winches"
        ],
        "Auto Lighting": [],
        "Auto Detailing and Car Care": [],
        "Auto Body and Paint": [],
        "Oil and Fluids": [ 
            "Motor Oil",
            "Antifreeze and Coolants",
            "Transmission, Brake and Steering Fluids"
        ],
        "Tools and Equipment": [ 
            "Car Battery Chargers and Jump Starters",
            "Diagnostic Tools",
            "Auto Repair Tools"
        ],
        "Auto Electronics": [ 
            "Car Stereos",
            "Power Inverters",
            "Dash Cams"
        ],
        "Auto Replacement Parts": [  
            "Replacement Parts",
            "Brakes",
            "Oil Filters",
            "Wiper Blades",
            "Engine Air Filters",
            "Spark Plugs"
        ]
    }
}